#encoding: utf-8
mail:                     # Настройки почтовых извещений
  enable: "no"            # yes/no
  login: "login"          # Логин от почтового сервера
  password: "password"    # Пароль от почтового сервера
  from: "from1"           # Адрес отображающийся в поле от кого
  to:                     # Список адресов доставки
        - "to1"
        - "to2"
urls:
  - "http://docs.pravo.ru"

hub_url: "http://127.0.0.1:4444"

users:
  - ["Логин",                         "Пароль",   "Имя",    "Фамилия",  "Телефон",  "Cпециализация",  "Наименование компании",    "ИНН",        "ОГРН",           "ОКПО",       "КПП",        "БИК",        "Кор. счет",            "Расчетный счет",       "Юридический адрес",      "Почтовый адрес"]
  - ["firstmonkeyparcsis@gmail.com",   "checking", "first",  "monkey",   "123",      "Юрист",          "Компания первой Мартышки", "1234567899", "9999987654321",  "1234567899", "123456789",  "123456789",  "9223372036854775807",  "9223372036854775807",  "Самара тц 'Вертикаль'",  "Самара тц 'Вертикаль'"]