urls:
  - "http:docs.pravo.ru"
users:
  - ["Логин",                         "Пароль",   "Имя",    "Фамилия",  "Телефон",  "Cпециализация",  "Наименование компании",    "ИНН",        "ОГРН",           "ОКПО",       "КПП",        "БИК",        "Кор. счет",            "Расчетный счет",       "Юридический адрес",      "Почтовый адрес"]
