require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'
require "rake"

options = [
    "MainPage",
    "UserPerson"
          ]

options.each do |name|
  Cucumber::Rake::Task.new(:debug) do |t|
    t.cucumber_opts = "features --format pretty -n "+name
  end
end

options.each do |name|
  Cucumber::Rake::Task.new(:all) do |t|
    log_dir = Dir[File.dirname(__FILE__) + '/../../logs/'].first
    t.cucumber_opts = "--format junit -n "+name+" --out "+"'"+log_dir+"'"
  end
end
